version: '3.3'

services:

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: cashmanager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  time-manager-api:
    build: ./cash-manager-back
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always